name: restyle

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-ts:
    name: 'Build Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - run: |
          yarn install --immutable
          yarn build
  lint-ts:
    name: 'Lint Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - run: |
          yarn install --immutable
          yarn lint
  test-ts:
    name: 'Test Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - run: |
          yarn install --immutable
          yarn test --forceExit
